### PR TITLE
scripts(docs release): commit changes only if there was any change.

### LINKED ISSUE #3528: Docsaurus publishing keeps failing on CI
### What happened?

In at least the last 2 release (probably more), Docusaurus (Detox website) publishing keeps failing due to some technical reasons related to our CI script, even though Detox gets successfully release to NPM alongside the Git tag, as it should:

```


> website@0.0.0 docusaurus /Users/builder/work/website
--
  | > docusaurus "docs:version" "19.x"
  |  
  | [docs]: version 19.x created!
  | git add .
  | git commit -m "Publish docs version 19.x"
  | On branch master
  | Your branch is up to date with 'origin/master'.
  |  
  | Changes not staged for commit:
  | (use "git add <file>..." to update what will be committed)
  | (use "git restore <file>..." to discard changes in working directory)
  | modified:   ../.npmrc
  |  
  | Untracked files:
  | (use "git add <file>..." to include in what will be committed)
  | ../detox-cli/.npmrc
  | ../detox/.npmrc
  |  
  | no changes added to commit (use "git add" and/or "git commit -a")
  | child_process.js:866
  | throw err;
  | ^
  |  
  | Error: Command failed: git commit -m "Publish docs version 19.x"
  | at checkExecSyncError (child_process.js:790:11)
  | at Object.execSync (child_process.js:863:15)
  | at Object.execSync (/Users/builder/work/node_modules/shell-utils/src/exec.js:8:6)
  | at buildDocsForVersion (/Users/builder/work/scripts/utils/releaseDocumentation.js:18:10)
  | at releaseDocsVersion (/Users/builder/work/scripts/utils/publishNewVersion.js:70:3)
  | at publishNewVersion (/Users/builder/work/scripts/utils/publishNewVersion.js:30:5)
  | at versionTagAndPublish (/Users/builder/work/scripts/ci.release.js:52:5)
  | at run (/Users/builder/work/scripts/ci.release.js:18:3)
  | at Object.<anonymous> (/Users/builder/work/scripts/ci.release.js:59:1)
  | at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  | status: 1,
  | signal: null,
  | output: [ null, null, null ],
  | pid: 96152,
  | stdout: null,
  | stderr: null
  | }
  | npm ERR! code ELIFECYCLE
  | npm ERR! errno 1
  | npm ERR! root@19.8.4 release: `node scripts/ci.release.js`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the root@19.8.4 release script.
  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /Users/builder/.npm/_logs/2022-08-03T11_10_51_563Z-debug.log
  | 1
  | cibuild: restoring buildkite workdir: /usr/local/var/buildkite-agent/builds/agent-153/wix-mobile-oss/detox
  | 🚨 Error: The command exited with status 1
  | user command error: exit status 1

```
Source: https://buildkite.com/wix-mobile-oss/detox/builds/983#0182633d-b98e-4cdb-a48f-298bc4c8282d

### What was the expected behaviour?

_No response_

### Was it tested on latest Detox?

- [ ] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

_No response_

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

### More data, please!

_No response_

### PR DESCRIPTION
**Pull request by asafkorem**
Fixes #3528.

The new command does git commit only if there were any changes to the docs website.

### CODE REVIEW

File: scripts/utils/releaseDocumentation.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ function buildDocsForVersion(version) {
     exec.execSync(`npm install`);
     exec.execSync(`npm run docusaurus docs:version ${version}`);
     exec.execSync(`git add .`);
-    exec.execSync(`git commit -m "Publish docs version ${version}"`);
+    exec.execSync(`git diff --quiet && git diff --staged --quiet || git commit -m "Publish docs version ${version}"`);
     exec.execSync(`git push origin ${process.env.BUILDKITE_BRANCH}`);
```
Comment (d4vidi) [inline scripts/utils/releaseDocumentation.js:19]: @asafkorem Nice!
I think we want to restrict this `push` for when something is in fact comitted, don't we?
