### PR TITLE
fix(android): Detox enable synchronization

### LINKED ISSUE #3461: Disabling synchronization on startup fails
### What happened?

I used the following code for launchapp:
```
    await device.launchApp({
      permissions: {notifications: 'YES', location: 'inuse'},
      launchArgs: { detoxEnableSynchronization: 0 }
    });
```
To get around an animation loop on the start up screen. However, it still gets stuck there. Here is the code between where it starts and where it gets stuck:
```
    await device.launchApp({
      permissions: {notifications: 'YES', location: 'inuse'},
      launchArgs: { detoxEnableSynchronization: 0 }
    });
    console.log(test_group_name, ' Synchronization Disabled');
    console.log(test_group_name, ' launch completed');
  });
  it(test_group_name + 'App launch & login', async () => {
      //Load app
      device.disableSynchronization();
      await device.reloadReactNative();
      await util.setLocation('30.01654', '31.431934');
      //StartupScreen
      await waitFor(element(by.id('STARTUP_SCREEN_BUTTON'))).toBeVisible().withTimeout(2000);
      await element(by.id('STARTUP_SCREEN_BUTTON')).tap();
```
The last two commands are never executed, and the problem is with animation synchronization because the console shows:
```
12:00:29.571 detox[162837] INFO:  [APP_STATUS] The app is busy with the following tasks:
• UI elements are busy:
  - Reason: Animations running on screen.
```

### What was the expected behaviour?

For animation loop to be ignored and push the button.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

launchapp in disable synchronization

### In what environment did this happen?

Detox version: 19.7.1
React Native version: 67.4
Node version: 16.15.0
Device model: Pixel XL
Android version: 11
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

### More data, please!

_No response_

### PR DESCRIPTION
**Pull request by jonathanmos**
## Description
Enable/disable the synchronization mechanism with a launch argument.

- This pull request addresses the issue described here: #3270

Fixes #3461

### CODE REVIEW

File: detox/android/detox/src/full/java/com/wix/detox/LaunchArgs.java [hunk 1]
```diff
@@ -36,6 +37,14 @@ public boolean hasURLBlacklist() {
         return InstrumentationRegistry.getArguments().containsKey(DETOX_BLACKLIST_URLS_ARG);
     }
 
+    public String getDetoxEnableSynchronization() {
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/LaunchArgs.java:40]:
```suggestion
    public String getEnableSynchronization() {
```

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt [hunk 2]
```diff
@@ -69,17 +64,11 @@ class ReactNativeIdlingResources constructor(
...
         Log.i(LOG_TAG, "Setting up Espresso Idling Resources for React Native")
-
         unregisterAll()
 
-        if (launchArgs.hasURLBlacklist()) {
-            val blacklistUrls = launchArgs.getURLBlacklist()
-            setBlacklistUrls(blacklistUrls)
-        }
-
+        setupUrlBlacklist()
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt:69]: Nice!

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt [hunk 3]
```diff
@@ -46,15 +46,10 @@ private class MQThreadReflected(private val queue: Any?, private val queueName:
...
-        internal var networkSyncEnabled: Boolean = true
-        )
-
-    {
-
+    private val reactContext: ReactContext,
+    internal var networkSyncEnabled: Boolean = true
+) {
     companion object {
-        private const val FIELD_UI_BG_MSG_QUEUE = "mUiBackgroundMessageQueueThread"
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt:57]: Yes, I guess it's about time to do that 😂

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt [hunk 4]
```diff
@@ -141,7 +141,8 @@ class ReactNativeIdlingResources constructor(
                 timersIdlingResource,
                 rnBridgeIdlingResource,
                 uiModuleIdlingResource,
-                animIdlingResource)
+                animIdlingResource
+            )
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt:145]: Not a fan of this style but okay

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt [hunk 5]
```diff
@@ -212,13 +219,8 @@ class ReactNativeIdlingResources constructor(
 
     private fun toFormattedUrlArray(urlList: String): List<String> {
         var formattedUrls = urlList
-        formattedUrls = formattedUrls.replace(Regex("""[()"]"""), "");
-        formattedUrls = formattedUrls.trim();
-        return formattedUrls.split(',');
-    }
-
-    fun setBlacklistUrls(urlList: String) {
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt:220]: good thinking (move to before all private's 👍🏻)

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt [hunk 6]
```diff
@@ -108,28 +97,39 @@ class ReactNativeIdlingResources constructor(
...
                 registerLooperAsIdlingResource(mqNativeModules)
             }
         }
     }
 
+    private fun setupUrlBlacklist() {
+        val launchArgs = LaunchArgs()
+        if (launchArgs.hasURLBlacklist()) {
+            val blacklistUrls = launchArgs.urlBlacklist
+            setBlacklistUrls(blacklistUrls)
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt:129]: Something feel off with the private method calling a public one. My suggestion, push `setBlackUrls` to something private and call it here. As for the publish method, [this](https://github.com/wix/Detox/blob/e2f62b8ad66df1b27ad658f3201d54e08201832f/detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeExtension.kt#L81) is an example of an equivalent case.

File: detox/test/e2e/12.animations.test.js [hunk 7]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
-    if(options.delay !== undefined) {
+    if (options.delay !== undefined) {
       await element(by.id('UniqueId_AnimationsScreen_delay')).replaceText(String(options.delay));
     }
 
     await element(by.id('UniqueId_AnimationsScreen_startButton')).tap();
   }
 
   describe.each(['JS', 'Native'])('(driver: %s)', (driver) => {
+    beforeEach(async () => {
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:29]: Cool

File: detox/test/e2e/12.animations.test.js [hunk 8]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
       await expect(element(by.id('UniqueId_AnimationsScreen_afterAnimationText'))).toExist();
     });
 
     it(`should not wait for an animation to complete while the synchronization is disabled`, async () => {
-      await device.disableSynchronization(); 
-      await _startTest(driver, {duration: 5000});
+      await device.disableSynchronization();
+      await _delay(800);
+      await _startTest(driver, { duration: 5000 });
+      await _delay(800);
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:63]: What behind this? Why 800 and why is it required to begin with?

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeExtension.kt [hunk 9]
```diff
@@ -39,7 +39,7 @@ object ReactNativeExtension {
             reloadReactNativeInBackground(it)
             val reactContext = awaitNewReactNativeContext(it, previousReactContext)
 
-            setupIdlingResources(reactContext, networkSyncEnabled)
+            setSynchronizationState(reactContext, networkSyncEnabled)
```
Comment (d4vidi) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeExtension.kt:42]: There's definitely a naming issue here. What does "state" mean? It's not descriptive enough.

File: detox/test/e2e/12.animations.test.js [hunk 10]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
+          detoxEnableSynchronization: 0
+        }
+      });
+
+      // The delays are necessary since we're running without synchronization
+      await _delay(800);
+      await element(by.text('RN Animations')).tap();
+      await _delay(800);
+      await _startTest('JS', { duration: 5000 });
+      await _delay(800);
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:85]: Again, why the multiple delays? A 5 seconds animation should be enough, shouldn't it?

File: detox/test/e2e/12.animations.test.js [hunk 11]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
   });
-});
 
-describe(':android: Native animations', () => {
-  it('should expect a native android-animator animation to be short-circuited / fully-completed', async () => {
-    await device.reloadReactNative();
-    await element(by.text('Native Animation')).tap();
+  describe('detoxEnableSynchronization', () => {
+    it('should launch without synchronization for detoxEnableSynchronization 0', async () => {
+      await device.launchApp({
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:73]: A descriptive helper (arrow?) function would be nice instead of these multiple `device.launchApp()` calls.

File: detox/test/e2e/12.animations.test.js [hunk 12]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
+        newInstance: true,
+        launchArgs: {
+          detoxEnableSynchronization: 0
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:76]: I just can't believe that this is the official Detox API 🤦🏻 Of course, not suggesting to change that ATM.

File: detox/test/e2e/12.animations.test.js [hunk 13]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
-    await expect(element(by.text('Animation Complete'))).toBeVisible();
+    it('should launch with synchronization for detoxEnableSynchronization 1', async () => {
+      await device.launchApp({
+        newInstance: true,
+        launchArgs: {
+          detoxEnableSynchronization: 1
+        }
+      });
+
+      await element(by.text('RN Animations')).tap();
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:104]: Introducing a driver in order to avoid this code duplication, would be nice.

**Review by d4vidi — CHANGES_REQUESTED** [review]
Hey, work is pretty good, overall 👍🏻
Though I did write a lot of notes, only a few of them actually contain concrete requests for changes.

**Comment by d4vidi** [comment]
@jonathanmos add "Fixes #3461"?

File: detox/test/e2e/12.animations.test.js (hunk 10 above)
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:78]: Remove

File: detox/test/e2e/12.animations.test.js [hunk 14]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
+        }
+      });
+
+      // The delays are necessary since we're running without synchronization
+      await _delay(800);
+      await element(by.text('RN Animations')).tap();
+      await _delay(800);
+      await _startTest('JS', { duration: 5000 });
+      await _delay(800);
+      await expect(element(by.id('UniqueId_AnimationsScreen_afterAnimationText'))).not.toExist();
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:79]:
```suggestion
      await expect(element(by.id('UniqueId_AnimationsScreen_afterAnimationText'))).not.toExist();
      
      await _delay(5000);
      await expect(element(by.id('UniqueId_AnimationsScreen_afterAnimationText'))).toExist();
```

File: detox/test/e2e/12.animations.test.js [hunk 15]
```diff
@@ -17,60 +14,106 @@ describe('React-Native Animations', () => {
...
+        launchArgs: {
+          detoxEnableSynchronization: 0
+        }
+      });
+
+      // The delays are necessary since we're running without synchronization
+      await _delay(800);
+      await element(by.text('RN Animations')).tap();
+      await _delay(800);
+      await _startTest('JS', { duration: 5000 });
```
Comment (d4vidi) [inline detox/test/e2e/12.animations.test.js:77]: Can settle on `<5000` 🤔

**Review by d4vidi — APPROVED** [review]
