### PR TITLE
fix(Android): RN instance listener - dynamic proxies for the rescue

### LINKED ISSUE #3492: [RN 68] Android backwards compatibility (RN .64): test project

### PR DESCRIPTION
**Pull request by d4vidi**
## Description

This is work made on top of #3504 (details within), which hasn't seem to successfully resolve the issue.
Fixes #3492.

### CODE REVIEW

**Comment by asafkorem** [comment]
Amazing

File: detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt [hunk 1]
```diff
@@ -82,3 +82,48 @@ open class ReactNativeLoadingMonitor(
         return rnInstanceManager.currentReactContext
     }
 }
+
+private interface DummyListenerIdentifier
+
+/**
+ * This baby bridges over RN's breaking change introduced in version 0.68:
```
Comment (asafkorem) [inline detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt:89]: 😆 💯
