### PR TITLE
Fix handling of ambiguous genymotion recipe matching

### LINKED ISSUE #4784: Fail Detox on genymotion alloc disambig
### Describe your idea

This is an undesired deduping mechanism, need to remove it:

```
12:34:56.789 detox[1234] i More than one Genymotion-Cloud recipe found for recipe name MyEmulator_SDK34:
--
  | MyEmulator_SDK34_arm64 (<uuid1>)
  | MyEmulator_SDK34 (<uuid2>)
  | Falling back to MyEmulator_SDK34_arm64
```

(you find yourself setting recipe A in the config and end up with recipe B)...

### PR DESCRIPTION
**Pull request by d4vidi**
## Description

- Fixes #4784

In this pull request, I have addressed the issue of Genymotion recipe disambiguation. Added the following:
- Throw an error when more than one recipe matches a query
- Aligned flow of 0 recipe matches: Throw an error instead of returning null. This is a better approach because the recipes service knows the error details best and therefore should be the one raising the problem.

---

> _For features/enhancements:_
 - [ ] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

### CODE REVIEW

File: detox/src/devices/allocation/drivers/android/genycloud/GenyRecipeQuerying.js [hunk 1]
```diff
@@ -1,3 +1,6 @@
+/**
+ * @param {import('./services/GenyRecipesService')} recipesService
+ */
 class GenyRecipeQuerying {
```
Comment (noomorph) [inline detox/src/devices/allocation/drivers/android/genycloud/GenyRecipeQuerying.js:1]: wrong jsdoc location - move it one line down

**Review by noomorph — APPROVED** [review]
Looks good, except for the misplaced jsdoc comment

File: detox/src/devices/allocation/drivers/android/genycloud/GenyRecipeQuerying.js (hunk 1 above)
Comment (d4vidi) [reply detox/src/devices/allocation/drivers/android/genycloud/GenyRecipeQuerying.js:1]: LOL

**Comment by d4vidi** [comment]
Thanks @noomorph, the PR is now ready for review so please have a more thorough look

File: detox/src/devices/allocation/drivers/android/genycloud/services/GenyRecipesService.js [hunk 2]
```diff
@@ -10,15 +10,18 @@ class GenyRecipesService {
   async getRecipeByName(recipeName) {
     const { recipes } = await this.genyCloudExec.getRecipe(recipeName);
     if (!recipes.length) {
-      return null;
+      throw new DetoxRuntimeError({
```
Comment (noomorph) [inline detox/src/devices/allocation/drivers/android/genycloud/services/GenyRecipesService.js:13]: Elegant. ;)
