### PR TITLE
PR (Issue #1176) - Stop Forcing -gpu host on android emulators

### LINKED ISSUE #1176: Stop forcing -gpu host when launching android emulator
#### Description
Launching an android emulator via the `detox test` command always uses the cli parameters `-gpu host` which will fail in some scenarios where host gpu emulation is not available. This flag should not be included allowing the emulator to launch with whatever gpu mode is specified in the config.ini. 

I believe the default behavior when an explicit gpu mode is not specified in the config.ini is to use the host gpu, anyway.

#### Steps to Reproduce
Run the `detox test -c <config>` command. Use a configuration of type `android.emulator` and select an avd name with a `config.ini` file that has an explicit hw.gpu.mode set.

e.g.
```
hw.gpu.mode=swiftshader_indirect
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: `10.0.7`
* React Native: `0.57.8`
* Node: `11.6.0`
* Device: `Android Emulator`
* Xcode: N/A 
* macOS: N/A
* Windows: `Windows 10 Pro v1703`

#### Device and verbose Detox logs
For the sake of brevity, only including the relevant error message portion of the log:
```
detox[1400] ERROR: [Emulator.js/SPAWN_FAIL] path\to\emulator -verbose -gpu host -no-audio @DEFAULT_EMULATOR failed with code 3221225477

emulator: ERROR: OpenGLES emulation failed to initialize. Please consider the following troubleshooting steps:

1. Make sure your GPU drivers are up to date.

2. Try software rendering: Go to Extended Controls > Settings > Advanced tab and change "OpenGL ES renderer (requires restart)" to "Swiftshader".

Or, run emulator from command line with "-gpu swiftshader_indirect". 3. Please file an issue to https://issuetracker.google.com/issues?q=componentid:192727 and provide your complete CPU/GPU info plus OS and display setup.
```

### PR DESCRIPTION
**Pull request by RyanThomas73**
Resolves #1176 

Only adds the `-gpu [gpu mode]` flags to the android `emulator` command if the `--headless` parameter is specified or if an explicit `--gpu [gpu mode]` cli argument is provided.

### CODE REVIEW

**Comment by noomorph** [comment]
@rotemmiz, looks good to me. Shall we merge?

File: detox/src/devices/android/Emulator.js [hunk 1]
```diff
@@ -93,9 +102,9 @@ class Emulator {
         default:
           return 'auto';
       }
-    } else {
-      return 'host';
     }
+
+    return undefined;
```
Comment (d4vidi) [inline detox/src/devices/android/Emulator.js]: @RyanThomas73 for backwards compatibility, please return `host` as the default.

Comment (RyanThomas73) [reply detox/src/devices/android/Emulator.js]: @d4vidi Returning host as the default reintroduces the problem where it will always include `-gpu host` with the emulator command preventing the emulator command from honoring an explicit gpu mode specific in the emulator config via `hw.gpu.mode=`

Comment (RyanThomas73) [reply detox/src/devices/android/Emulator.js]: We could choose a specific value to map to `undefined` so it uses the emulator config default (e.g. `detox test .... --gpu default`) but I feel its better the way it is in the PR now, the user shouldn't have to explicitly specify default to get the default behavior from the emulator.

Comment (d4vidi) [reply detox/src/devices/android/Emulator.js]: Yes, you are right - I was not aware of that.
Nevertheless the issue of back-compatibility still _is_ concerning (keeping the community happy). That being said, I take it that the crucial use cases are of the CI, where typically emulators are run `headless`, which isn't affected in this case. So, bottom line here - I'll approve and merge.
Thank you :)
